sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

stages:
  - name: deploy

# Only build tags
if: tag IS present

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

before_deploy:
  - cd .build
  - npm install
  - npx gulp
  - echo "Listing built files"
  - ls ./build/
