sudo: false

language: node_js
node_js:
  - node

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: $GITHUB_REPO_NAME
    tags: true

cache:
  directories:
    - node_modules

before_deploy:
  - cd .build
  - npm install
  - npx gulp
  - echo "Listing built files"
  - ls ./build/
