title: KP Liberation

baseUrl: liberation.killahpotatoes.de

description: A persistent campaign for ArmA3 to liberate an area that will span several weeks of real time

repository: KillahPotatoes/KP-Liberation

safe: true

theme: null

highlighter: rouge

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: [.editorconfig, .gitignore, README.md, CNAME, Gemfile, Gemfile.lock, serve.sh]

sass:
    sass_dir: _scss
