name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: veteran29/sqflint@master
        with:
          args: --directory Missionframework

  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: docker://node:10-alpine
        name: Setup Node

      - name: Install dependencies
        working-directory: ./_tools
        run: npm install

      - name: Assemble and pack
        working-directory: ./_tools
        run: npx gulp

