name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: veteran29/sqflint@master
        with:
          args: --exit e --directory Missionframework
      - name: LS
        run: ls
